test5

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -117,6 +117,11 @@ jobs:
         with:
           name: helm-values
 
+      - name: Debug values.yaml
+        run: |
+          ls -la values.yaml
+          cat values.yaml | grep -A 10 "backendReport:" || echo "backendReport section NOT found"
+
       - name: Deploy with Helm
         run: |
           helm upgrade --install sausage-store \
@@ -126,8 +131,14 @@ jobs:
             -f values.yaml \
             --set global.imagePullPolicy=Always \
             --set backend.image=${{ secrets.DOCKER_USER }}/sausage-backend:${{ github.sha }} \
+            --set backend.containerPort=8080 \
+            --set backend.service.port=8080 \
             --set frontend.image=${{ secrets.DOCKER_USER }}/sausage-frontend:${{ github.sha }} \
+            --set frontend.containerPort=80 \
+            --set frontend.service.port=80 \
             --set backendReport.image=${{ secrets.DOCKER_USER }}/sausage-backend-report:${{ github.sha }} \
+            --set backendReport.containerPort=8080 \
+            --set backendReport.service.port=8080 \
             --set infra.postgresql.env.POSTGRES_PASSWORD="${{ secrets.POSTGRES_PASSWORD }}" \
             --set infra.mongodb.env.MONGO_INITDB_ROOT_PASSWORD="${{ secrets.MONGO_PASSWORD }}" \
             --set backend.env.postgresPassword="${{ secrets.POSTGRES_PASSWORD }}"
